config/routes.rb
Rails.application.routes.draw do

  resources :groups do
    collection do
      delete 'destroy_multiple_members'
      delete '(:id)/leave_group' => 'groups#leave_group', :as => 'leave_group'
      get '(:id)/calculate_split_expenses' => 'groups#calculate_split_expenses', :as =>'calculate_split_expenses'
      get '(:id)/show_bills' => 'groups#show_bills', :as => 'show_bills'
    end
  end

  resources :bills, :only =>[:show, :new, :create, :destroy, :index, :update, :edit]

  devise_for :users

  root :to => redirect('/groups')

end

app/models/group.rb
class Group < ActiveRecord::Base
  include BillManager
  has_and_belongs_to_many :users
  validates :name, :presence => true

  def invite_member new_member
    users << new_member if !users.include? new_member
  end

  def kick_member member
    users.delete(member) if users.include? member
    bills.where(user_id: member.id).destroy_all
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
  end

  def create
    @group = current_user.create_group(params[:group][:name])
    if @group.save
      current_user.groups << @group
      redirect_to group_url(id: @group.id)
    else
      render :action => "new"
    end
  end

  def index
    @groups = current_user.groups
    render :index
  end

  def update
    set_group
    new_member=User.where(username: params[:member_username].first.capitalize).first
    current_user.invite_member_to_group(new_member,@group)
    NotifyMailer.invited_to_group(new_member,@group).deliver

    redirect_to group_url(id: @group.id)
  end

  def show
    set_group
  end

  def leave_group
    set_group
    current_user.leave_group(@group)
    redirect_to groups_path
  end

  def destroy
    set_group
    current_user.destroy_group(@group)
    redirect_to new_group_url
  end

  def destroy_multiple_members
    set_group
    members_ids = params[:members_ids].split(',')
    current_user.kick_multiple_members(members_ids,@group)
    redirect_to group_url(id: @group.id)
  end

  def calculate_split_expenses
    set_group
    @group_split = @group.calculate_split_expenses
  end

  private
  def set_group
    @group = Group.find(params[:id])
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/calculate_split_expenses.html.erb
<% @group_split.each do |user, amount| %>
  <div class="panel panel-default">
    <%= label_tag user %>
    <% if amount > 0 %>
      Must pay: <%= label_tag number_to_currency(amount.abs, unit:'€')%>
      <%else%>
    Should receive: <%= label_tag number_to_currency(amount.abs, unit:'€')%>
      <%end%>
  </div>
<% end %>

app/views/groups/index.html.erb
<% @groups.each do |group| %>
  <div class="panel panel-default">
       <b><%= label_tag group.name%></b><br>



  <div class="btn-group btn-group-xs" role="group" aria-label="..." style="display :inline;" >
          <%= link_to "Calculate", calculate_split_expenses_groups_path(group, group.id),class:"btn btn-default"%>
          <%= link_to "Show Bills", bills_path(group_id: group.id),class:"btn btn-default show-bills"%>
      <% if current_user.id == group.owner_id %>
          <%= link_to "Edit", group_path(group.id),class:"btn btn-default"%>
      <%end%>
  </div>

    <% if current_user.id != group.owner_id %>
      <%=form_tag leave_group_groups_path(group.id), method: :delete, class: "leave-group-form", style: "float: left;" do  %>
        <div class="btn-group btn-group-xs" role="group" aria-label="...">
          <%= submit_tag "Leave Group", class: "btn btn-default group-leave", id: group.id%>
        </div>
      <%end%>
    <%end%>




  </br>
    <div class="panel-body">
      <% group.users.each do |user| %>
       <%= label_tag user.username, nil, class:"label label-default" %>
      <% end %>

    </div>
  </div>
<% end %><%= link_to "Create new Group", new_group_path, class: "btn btn-primary"%> <br>

app/views/groups/new.html.erb
  <%=form_for @group, :html => {:controller => "groups" , :action => "create", :method => "post"} do |f| %>
  <div class="form-group">
    <%= f.label :name,"Group Name"%>
    <%= f.text_field :name, class: "form-control"%>
      <br>
      <%= f.submit "Create Group", class: "btn btn-primary"%>
  </div>
    <%= @group.errors.full_messages.first if @group.errors.any? %>
  <%end%>

app/views/groups/show.html.erb
<div class='content'>
<h4> <%=label_tag "Group: " + @group.name %></h4>
  <h5> <%=label_tag "Owner: " +User.find(@group.owner_id).username %></h5>

  <% if @group.users.count > 1 %>
    <div id='members-container' class='members-container panel panel-default'>
      <div>Group Members</div>
      <div class="panel-body">
           <% @group.users.each do |u| %>
            <% if u.id != @group.owner_id%>
              <%= label_tag u.username,nil, class: 'label label-default select_members', id: u.id %>
            <% end %>
           <% end %>
      </div>
    </div>
      <%= form_tag destroy_multiple_members_groups_path, method: :delete do %>
        <%= hidden_field_tag :members_ids, nil%>
        <%= hidden_field_tag :id, @group.id %>
        <%= submit_tag "Remove selected members", class: 'btn-primary btn delete_members'%>
      <% end %>
  <% else%>
      <div class="panel panel-body panel-default">
    <div>This group has no users, invite more users so you can start splitting the bills!</div>
      </div>
  <%end%>
  <%=form_for @group, :html => {:controller => "groups", :action => "update", :method => "patch"} do%>
    <%= text_field "member_username", nil, id: @group.id, placeholder:"Member to be invited", style: "margin-top:20px;"%>
    <%= submit_tag "Invite", class: 'btn-primary btn' %>
  <% end %>
  </br>
  <div class="delete">
  <%=form_for @group, :html => {:controller => "groups" , :action => "destroy", :method => "delete"} do  %>
  <%= submit_tag "Delete Group", class: "btn btn-danger group-delete", id: @group.id%>
  <%end%>
  </div>
</div>

app/views/groups/show_bills.html.erb
<% @bills.each do |bill|%>
  <div class="panel panel-default">
    <%= label_tag User.find(bill.user_id).username %> <%= label_tag bill.description%> <br>
    <%= label_tag bill.amount %>
  </div>
<% end %>