config/routes.rb
Rails.application.routes.draw do

  resources :groups do
    collection do
      delete 'destroy_multiple_members'
      delete '(:id)/leave_group' => 'groups#leave_group', :as => 'leave_group'
      get '(:id)/calculate_split_expenses' => 'groups#calculate_split_expenses', :as =>'calculate_split_expenses'
      get '(:id)/show_bills' => 'groups#show_bills', :as => 'show_bills'
    end
  end

  resources :bills, :only =>[:show, :new, :create, :destroy, :index, :update, :edit]

  devise_for :users

  root :to => redirect('/groups')

end

app/views/shared/_navbar.html.erb
<nav role="navigation" class="navbar navbar-inverse">
  <div id="navbarCollapse" class="collapse navbar-collapse">

    <ul class="nav navbar-nav navbar-left">
      <li><span id="left-menu" class="fa fa-bars fa-2x"></span></li>

    <div class="navbar-center navbar-brand">
      <%= hidden_field_tag "bill_group", nil%>
      <a href="#" data-toggle="dropdown" class="nav dropdown-toggle">Create Bill<b class="caret"></b></a>
      <ul class="dropdown-menu">
        <% if current_user %>
        <% current_user.groups.each do |group| %>
          <li> <%=link_to group.name, new_bill_path(group_id: group.id), class_id: group.id, id:"group_id", class: 'dropdown-link' %></li>
          <%end%>
        <%end%>
      </ul>
    </div>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Bills", bills_path %></li>
    </ul>
  </div>
</nav>

app/views/shared/_side_navbar.html.erb
<nav class="navbar navbar-inverse navbar-custom col-xs-4">
  <ul class="nav nav-pills nav-stacked">
    <li><%= link_to "Groups", groups_path %></li>
    <li><%= link_to "Bills", bills_path(user_id: current_user.id) if current_user %></li>
    <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
    <li><%= link_to "History", '#' %></li>
    <li><%= link_to "About", '#' %></li>
  </ul>
</nav>